### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by lDarryll** [Paranioar/SGRAF#15]
I am very interested in your work (SGRAF). I now encounter a visualization problem, that is, how to visualize the results of image retrieval text and the results of text retrieval image (as shown in the figure below). If it's convenient for you, please provide the code of visualization results. Thank you very much
![C57BD5CC-3539-465D-A802-BEEA208EE7F4](https://user-images.githubusercontent.com/34019070/162561859-e59c526a-fc5d-4c1a-8811-977731ca1216.JPG)
!

**Comment by Paranioar** [comment]
> I am very interested in your work (SGRAF). I now encounter a visualization problem, that is, how to visualize the results of image retrieval text and the results of text retrieval image (as shown in the figure below). If it's convenient for you, please provide the code of visualization results. Thank you very much ![C57BD5CC-3539-465D-A802-BEEA208EE7F4](https://user-images.githubusercontent.com/34019070/162561859-e59c526a-fc5d-4c1a-8811-977731ca1216.JPG) !

You can just align the topK index with id_mapping to obtain the images and texts.
In the future, I will publish an image-text matching benchmark and integrate relevant codes of visualization and statistics.

**Comment by Paranioar** [comment]
I have updated related code. Please check it in this project. Thanks for the interest in our project.
