### ISSUE TITLE
About the formula in the paper

### ISSUE THREAD

**Issue by luckykidsGL** [Paranioar/SGRAF#19]
Hello author, I'm reading your paper. In the paper, the implementation of formulas 1, 3, 4, 5 is given in github where the code is located? As for the learnable parameter W in formula 1, I could not find the corresponding position in the code. Looking forward to your answer, thank you

**Comment by Paranioar** [comment]
> Hello author, I'm reading your paper. In the paper, the implementation of formulas 1, 3, 4, 5 is given in github where the code is located? As for the learnable parameter W in formula 1, I could not find the corresponding position in the code. Looking forward to your answer, thank you

Please check the [model.py](https://github.com/Paranioar/SGRAF/blob/main/model.py) for details.
