### ISSUE TITLE
Flickr 30k数据集提取的区域特征

### ISSUE THREAD

**Issue by songbohui** [Paranioar/SGRAF#20]
你好，作者，我最近看到您这篇论文实验细节中，用到了Flickr 30k数据集，还提取了其区域特征，我想请问一下在哪里能下载论文实施细节提到的Flickr 30k数据集区域特征，麻烦看到了，回复一下，急用，谢谢！

**Comment by Paranioar** [comment]
> 你好，作者，我最近看到您这篇论文实验细节中，用到了Flickr 30k数据集，还提取了其区域特征，我想请问一下在哪里能下载论文实施细节提到的Flickr 30k数据集区域特征，麻烦看到了，回复一下，急用，谢谢！

The precomputed image features of Flickr30K are extracted from the raw Flickr30K images using the bottom-up attention model from (model_code)[https://github.com/peteanderson80/bottom-up-attention].

All the image features and vocabularies can be downloaded from (feature_files)[https://www.kaggle.com/datasets/kuanghueilee/scan-features]
