### ISSUE TITLE
A request over the info. of your used GPU?

### ISSUE THREAD

**Issue by Starboy-at-earth** [Paranioar/SGRAF#3]

**Comment by Starboy-at-earth** [comment]
Dear author:
       Could you please tell me whether two 2080Tis are enough for reproducing your results? Thank you in advance!!!

**Comment by Paranioar** [comment]
I use one NVIDIA Tesla V100 of 32G or P40 of 24G.
In my mind, the older version in the lab can run on two 1080Tis.

**Comment by Paranioar** [comment]
> Dear author:
> Could you please tell me whether two 2080Tis are enough for reproducing your results? Thank you in advance!!!

I use one NVIDIA Tesla V100 of 32G or P40 of 24G.
In my mind, the older version in the lab can run on two 1080Tis.

**Comment by Starboy-at-earth** [comment]
Thank you for your in-time reply. But I am little confused about your mentioned "older version". What is the meanting of it? Does it means the somewhat ablated version of your proposed net?

**Comment by Starboy-at-earth** [comment]
@Paranioar Thank you for your in-time reply! Your answer is very important to me. But I am still  a little confused about your mentioned "the older version". Does that mean a somewhat ablated version of your proposed network?

**Comment by Paranioar** [comment]
> @Paranioar Thank you for your in-time reply! Your answer is very important to me. But I am still a little confused about your mentioned "the older version". Does that mean a somewhat ablated version of your proposed network?

Yes, that is the version based on multi-gpus for ECCV2020. The main difference is that we compute the global image embedding with a simple graph.
