### ISSUE TITLE
run

### ISSUE THREAD

**Issue by rabrabrab** [Paranioar/SGRAF#5]
i have set the virtual environment of my pycharm as same as torch1.2.0 and python2.7. But i can't run through after my train when i want to evaluate the model. it shows indexerror with indices for array. Is something wrong with my environment or my data or some other probability? I tried to solve it with my friends but we found that the code is totally correct. But it still can't successfully eval on my computer. This problem had been haunted me for few days.  Thank u.

**Comment by Paranioar** [comment]
> i have set the virtual environment of my pycharm as same as torch1.2.0 and python2.7. But i can't run through after my train when i want to evaluate the model. it shows indexerror with indices for array. Is something wrong with my environment or my data or some other probability? I tried to solve it with my friends but we found that the code is totally correct. But it still can't successfully eval on my computer. This problem had been haunted me for few days. Thank u.

Please show more details.
What and where was the error reported？And what is the size of related features?
Our recommended environment is **Python 2.7, Pytorch0.4** which may be not the cause of this problem.

**Comment by rabrabrab** [comment]
well，i changed my torch to 0.4 just now and another error showed.
the index error is in the second photo.
I'm sorry about that…



发自我的iPhone


------------------ Original ------------------
From: Ronnie_IIAU ***@***.***&gt;
Date: Wed,Mar 31,2021 10:40 AM
To: Paranioar/SGRAF ***@***.***&gt;
Cc: rabrabrab ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Paranioar/SGRAF] run (#5)





  
i have set the virtual environment of my pycharm as same as torch1.2.0 and python2.7. But i can't run through after my train when i want to evaluate the model. it shows indexerror with indices for array. Is something wrong with my environment or my data or some other probability? I tried to solve it with my friends but we found that the code is totally correct. But it still can't successfully eval on my computer. This problem had been haunted me for few days. Thank u.
  
Please show more details.
 What and where was the error reported？And what is the size of related features?
 Our recommended environment is Python 2.7, Pytorch0.4 which may be not the cause of this problem.

**Comment by Paranioar** [comment]
> well，i changed my torch to 0.4 just now and another error showed. the index error is in the second photo. I'm sorry about that… 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Ronnie_IIAU ***@***.***&gt; Date: Wed,Mar 31,2021 10:40 AM To: Paranioar/SGRAF ***@***.***&gt; Cc: rabrabrab ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [Paranioar/SGRAF] run (#5) i have set the virtual environment of my pycharm as same as torch1.2.0 and python2.7. But i can't run through after my train when i want to evaluate the model. it shows indexerror with indices for array. Is something wrong with my environment or my data or some other probability? I tried to solve it with my friends but we found that the code is totally correct. But it still can't successfully eval on my computer. This problem had been haunted me for few days. Thank u. Please show more details. What and where was the error reported？And what is the size of related features? Our recommended environment is Python 2.7, Pytorch0.4 which may be not the cause of this problem. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Photo？Where is it？

**Comment by rabrabrab** [comment]
![0331_2](https://user-images.githubusercontent.com/81627288/113085070-c0b32f80-9211-11eb-8185-1d30bb5b3184.jpg)
![0331_1](https://user-images.githubusercontent.com/81627288/113085099-cad52e00-9211-11eb-92bb-a1c7cb23acba.jpg)
0331_1 is the old pronblem, 0331_2 is the new one.Sorry

**Comment by Paranioar** [comment]
Firstly, if you use pytorch0.4, you should train from scratch because of the different variable definitions.
Secondly, please provide the shape of **img_emb,img_embs,ids** and the max value of ids during the whole process.

**Comment by Paranioar** [comment]
> ![0331_2](https://user-images.githubusercontent.com/81627288/113085070-c0b32f80-9211-11eb-8185-1d30bb5b3184.jpg)
> ![0331_1](https://user-images.githubusercontent.com/81627288/113085099-cad52e00-9211-11eb-92bb-a1c7cb23acba.jpg)
> 0331_1 is the old pronblem, 0331_2 is the new one.Sorry

Firstly, if you use pytorch0.4, you should train from scratch because of the different variable definitions.
Secondly, please provide the shape of **img_emb, img_embs, ids** and the max value of **ids** during the whole process.

**Comment by Paranioar** [comment]
Firstly, if you use pytorch0.4, you should train from scratch because of the different variable definitions.
Secondly, when using pytorch1.2, please provide the shape of **img_emb, img_embs, ids** and the max value of **ids** during the whole process.

**Comment by rabrabrab** [comment]
ok, actually i prefer torch1.2, because i have seen some other people had run successfully by this environment. Here the debug pictures are. The torch version is 1.2. Thanks  for your reply~
![ids](https://user-images.githubusercontent.com/81627288/113089975-51423d80-921b-11eb-9804-780546e62cc8.jpg)
![img_emb_shape](https://user-images.githubusercontent.com/81627288/113089976-51423d80-921b-11eb-95f0-3b2eeba6c233.jpg)
![img_embs_shape](https://user-images.githubusercontent.com/81627288/113089981-530c0100-921b-11eb-9b98-40207b89f8d6.jpg)

**Comment by Paranioar** [comment]
Change this code to 【img_embs[ids, :, :] = img...】
