### ISSUE TITLE
questions about visualization

### ISSUE THREAD

**Issue by xixiareone** [Paranioar/SGRAF#6]
Hello, I am very interested in your work, can you share the code for visual query 
Many thanks!

**Comment by Paranioar** [comment]
Actually, it is not complex. 
We first save the **attention weights (SAF β)** and **cosine distance (SGR α)** as **.npy file**.
We then translate the **.npy file** into **.xlsx file** and match color in Excel.

**Comment by Paranioar** [comment]
> Hello, I am very interested in your work, can you share the code for visual query
> Many thanks!

Actually, it is not complex.
We first save the **attention weights (SAF β)** and **cosine distance (SGR α)** as **.npy file**.
We then translate the **.npy file** into **.xlsx file** and match color in Excel.
