### ISSUE TITLE
How to test on MSCOCO5K？

### ISSUE THREAD

**Issue by Arlen-yuzu** [Paranioar/SGRAF#7]
code evaluation.py seems to test on mscoco1k
how to test on 5k?

**Comment by Paranioar** [comment]
> code evaluation.py seems to test on mscoco1k
> how to test on 5** split="testall", fold5=False**

> code evaluation.py seems to test on mscoco1k
> how to test on 5k?

**split="testall", fold5=False** for MSCOCO 5K；
**split="testall", fold5=True** for MSCOCO1K；
Do not use **split="test", fold5=False** for MSCOCO1K which only includes 1000 images & 5000 captions and which produces higher but unfair results.

**Comment by Paranioar** [comment]
> code evaluation.py seems to test on mscoco1k
> how to test on 5k?

Please use **split="testall", fold5=False** for MSCOCO 5K and **split="testall", fold5=True** for MSCOCO1K；
Do not use **split="test", fold5=False** for MSCOCO1K which only includes 1000 images & 5000 captions and which produces **higher but unfair** results.

**Comment by Arlen-yuzu** [comment]
Thank you so much!
Could you tell me how to get visual pictures of global&local alignments result?

**Comment by Paranioar** [comment]
> Thank you so much!
> Could you tell me how to get visual pictures of global&local alignments result?

Please check the issue [#6].
