### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by KevinLight831** [Paranioar/SGRAF#8]

**Comment by KevinLight831** [comment]
data.py
line44: image = torch.Tensor(self.images[img_id])
--> image = torch.Tensor(self.images[int(img_id)])

**Comment by KevinLight831** [comment]
model.py
line122:cap_emb = (cap_emb[:, :, :cap_emb.size(2)/2] + cap_emb[:, :, cap_emb.size(2)/2:])/2
-->cap_emb = (cap_emb[:,:,:cap_emb.size(2)//2] + cap_emb[:,:,cap_emb.size(2)//2:])/2

**Comment by Paranioar** [comment]
> model.py
> line122:cap_emb = (cap_emb[:, :, :cap_emb.size(2)/2] + cap_emb[:, :, cap_emb.size(2)/2:])/2
> -->cap_emb = (cap_emb[:,:,:cap_emb.size(2)//2] + cap_emb[:,:,cap_emb.size(2)//2:])/2

![image](https://user-images.githubusercontent.com/37319709/114995994-fb36f080-9ed0-11eb-9a8d-65a4878b411a.png)

**Comment by KevinLight831** [comment]
sorry, i was too rude and careless.

**Comment by Paranioar** [comment]
> sorry, i was too rude and careless.

Never mind. 
Actually, most recent SOTAs are based on python2.7 and achieve lower performance with the same codes on python3.*
It is really meaningful to find out the difference, such as '/' or '//'，'open(path,'rb')' or 'open(path,'r')', ‘iteritems()’, etc.
I’m looking forward to your reproduction with python3.* where you may debug and adjust some details.

**Comment by Paranioar** [comment]
[pytorch_python版本.pdf](https://github.com/Paranioar/SGRAF/files/6340877/pytorch_python.pdf)
Thanks for the exploration and discussion from [**KevinLight831**](https://github.com/KevinLight831).
We will get an insight into this significant issue and create a new branch for **python3.6**.
Other issues are also instructive, [**VSRN**](https://github.com/KunpengLi1994/VSRN/issues/15), [**VSE++**](https://github.com/fartashf/vsepp/issues/12), etc.

**Comment by zt-1026** [comment]
> sorry, i was too rude and careless.

Hello, what's  your the results of final experiment with Python 3 and whether it has been reduced，Look forward to your reply.

**Comment by zt-1026** [comment]
> sorry, i was too rude and careless.

Hello, what's the results of  your final experiment with Python 3 and whether it has been reduced，Looking forward to your reply.
